const COMMON = ["the","be","to","of","and","a","in","that","have","it","for","not","on","with","he","as","you","do","at","this","but","his","by","from","they","we","say","her","she","or","an","will","my","one","all","would","there","their","what","so","up","out","if","about","who","get","which","go","me","when","make","can","like","time","no","just","him","know","take","people","into","year","your","good","some","could","them","see","other","than","then","now","look","only","come","its","over","think","also","back","after","use","two","how","our","work","first","well","way","even","new","want","because","any","these","give","day","most","us","great","between","need","large","must","big","long","much","right","still","house","world","next","head","hand","state","never","life","old","keep","school","city","tree","run","while","away","small","home","open","same","far","left","help","own","line","turn","move","live","found","tell","ask","kind","off","put","play","read","near","set","seem","night","three","bring","end","hear","story","walk","hard","stop","miss","enough","eat","side","real","again","face","watch","eye","wait","cross","yet","stand","word","start","might","late","grow","write","letter","point","land","close","door","name","fast","south","voice","family","carry","plant","cover","food","sun","four","order","half","reach","hold","fire","once","learn","girl","earth","done","river","north","sea","draw","high","feet","car","light","pass","road","rain","rule","pull","cold","always","music","those","both","mark","often","table","piece","few","best","idea","body","rock","care","group","love","together","got","step","children","money","clear","certain","gold","build","ship","room","plan","figure","star","box","field","rest","correct","able","behind","strong","class","nothing","complete","drive","front","teach","week","final","green","quick","develop","ocean","warm","free","minute","wonder","true","check","full","hot","sing","listen","fly","lead","cry","dark","note","above","paper","cut","power","town","fine","fall","already","sure","dog","question","early","ready","simple","leave","quiet","natural","stone","color","animal","fact","age","gone","possible","heart","record","morning","hundred","island","special","young","smell","sister","gave","third","planet","represent","allow","vowel","rope","settle","stay","told","nine","weight","indicate"];

const MEDIUM = ["although","continue","example","important","different","remember","consider","probably","position","surface","government","possible","national","include","describe","movement","material","through","between","problem","without","general","produce","million","provide","language","perhaps","picture","develop","machine","product","several","believe","company","program","finally","measure","question","industry","society","student","teacher","business","complete","practice","certain","process","system","quality","experience","personal","physical","building","interest","together","attention","knowledge","activity","evidence","structure","education","pressure","property","research","analysis","strategy","response","standard","training","security","function","resource","decision"];

const HARD = ["acknowledge","circumstance","comprehensive","determination","extraordinary","fundamentally","immediately","infrastructure","jurisdiction","knowledgeable","legitimately","manufacturing","nevertheless","opportunities","philosophical","qualification","revolutionary","sophisticated","technological","understanding","vulnerability","approximately","bureaucratic","consciousness","discrimination","entrepreneurial","hypothetical","implementation","miscellaneous","predominantly","rehabilitation","simultaneously","transformation","unconventional","visualization","psychological","environmental","investigation","communication","responsibility","administration","representative","characteristic","entertainment","internationally","appropriately","concentration","controversial","disappointment","establishment"];

export function generateText(count: number, difficulty: string): string {
  let pool: string[];
  switch (difficulty) {
    case "easy": pool = COMMON; break;
    case "medium": pool = [...COMMON, ...MEDIUM]; break;
    case "hard": pool = [...COMMON.slice(80), ...MEDIUM, ...HARD]; break;
    case "superhard": pool = [...MEDIUM, ...HARD]; break;
    default: pool = COMMON;
  }
  const words: string[] = [];
  for (let i = 0; i < count; i++) words.push(pool[Math.floor(Math.random() * pool.length)]);
  return words.join(" ");
}
